r"""
PYTHON MIRROR OF A JSON FILE  (generated by build_mirror.py - do not edit by hand)

Source JSON : 05_Videos/solver_co_current.json
Size        : 389 bytes
MD5         : 42eef1bd6c050912c40fc16cc96640ce
SHA-256     : 466a2f615bff06cb02f78fc4e9f4f32f4e773a432e2aedb53bf19d43338093b2

What it holds
    Settings and summary numbers of the co-current solver video

How the JSON was made (provenance)
    Evidence      : CONFIRMED - the writer script's json.dump names this file
    Writer script : tools/make_solver_video.py
    Working-tree  : 12_figures/video/solver_co_current.json
    Note          : file name pattern solver_%s.json in the script

Contents
    top level: object with 14 keys
      mode                               str
      f_interdig                         int
      frames                             int
      fps                                int
      simple_iterations                  int
      velocity_snapshots                 int
      u_in_mm_s                          float
      u_out_mm_s                         float
      speed_ratio                        float
      transit_s                          float
      eta                                float
      Tp_mean_K                          float
      Tp_std_K                           float
      energy_error_pct                   float

Guarantee
    to_json_text() returns the source JSON byte for byte (checked when this file was built,
    and again every time check_mirror.py runs). DATA is the same data as the JSON, key order
    included. JSON null/true/false are None/True/False; NaN / Infinity appear as NAN / INF.

Use
    print the JSON text :  python3 16_JSON_Python_Mirror/mirror/05_Videos/solver_co_current.py
    get DATA in Python  :  from grail_json import load
                           d = load("05_Videos/solver_co_current")
"""

NAN = float("nan")
INF = float("inf")

SOURCE_JSON = "05_Videos/solver_co_current.json"
SOURCE_MD5 = "42eef1bd6c050912c40fc16cc96640ce"
JSON_FORMAT = {'indent': 1, 'separators': None, 'ensure_ascii': True, 'trailing_newline': False}

DATA = {
    "mode": "co_current",
    "f_interdig": 0,
    "frames": 320,
    "fps": 20,
    "simple_iterations": 518,
    "velocity_snapshots": 52,
    "u_in_mm_s": 7.447719581072587,
    "u_out_mm_s": 25.54702631818908,
    "speed_ratio": 3.4301810158257746,
    "transit_s": 90.17,
    "eta": 0.5966969753920134,
    "Tp_mean_K": 315.03906331342665,
    "Tp_std_K": 6.737002959937468,
    "energy_error_pct": -1.3725850879534603e-05,
}


def to_json_text():
    """Rebuild the original JSON text from DATA (byte-identical to SOURCE_JSON)."""
    import json
    kw = {"indent": JSON_FORMAT["indent"], "ensure_ascii": JSON_FORMAT["ensure_ascii"]}
    if JSON_FORMAT["separators"]:
        kw["separators"] = tuple(JSON_FORMAT["separators"])
    return json.dumps(DATA, **kw) + ("\n" if JSON_FORMAT["trailing_newline"] else "")


if __name__ == "__main__":
    import sys
    sys.stdout.write(to_json_text())
