#!/usr/bin/env python3
"""Build the Python mirror of every JSON file in the GRAIL package.

    python3 16_JSON_Python_Mirror/build_mirror.py

For each JSON file listed in provenance.csv, this writes one .py file under mirror/, at the same
relative path (…/name.json -> mirror/…/name.py). The .py file holds:

  DATA          exactly the same data as the JSON, written as a readable Python literal
  JSON_FORMAT   the json.dumps settings that reproduce the original file byte for byte
  to_json_text  a function that turns DATA back into the original JSON text

A mirror file is written ONLY if to_json_text() gives back the original file byte for byte.
If no json.dumps setting reproduces a file exactly, the build stops and says which file; it never
writes an approximate mirror. The JSON files themselves are only read, never changed.
Standard library only (json, csv, hashlib).
"""
import os, sys, csv, json, math, hashlib, runpy

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MIRROR = os.path.join(HERE, "mirror")
WIDTH = 100


def md5(b):
    return hashlib.md5(b).hexdigest()


def sha256(b):
    return hashlib.sha256(b).hexdigest()


# ------------------------------------------------------------------ JSON format detection
def dump(data, fmt):
    kw = {"indent": fmt["indent"], "ensure_ascii": fmt["ensure_ascii"]}
    if fmt["separators"]:
        kw["separators"] = tuple(fmt["separators"])
    return json.dumps(data, **kw) + ("\n" if fmt["trailing_newline"] else "")


def detect_format(data, text):
    for indent in (1, 2, 4, None, 0, 3):
        for seps in (None, [",", ":"], [", ", ": "], [",", ": "]):
            for ea in (True, False):
                for nl in (False, True):
                    fmt = {"indent": indent, "separators": seps, "ensure_ascii": ea, "trailing_newline": nl}
                    if dump(data, fmt) == text:
                        return fmt
    return None


# ------------------------------------------------------------------ readable Python literal
IND = "    "


def scalar(v):
    if v is None:
        return "None"
    if v is True:
        return "True"
    if v is False:
        return "False"
    if isinstance(v, int):
        return repr(v)
    if isinstance(v, float):
        if math.isnan(v):
            return "NAN"
        if math.isinf(v):
            return "INF" if v > 0 else "-INF"
        return repr(v)          # repr round-trips every float exactly
    if isinstance(v, str):
        return json.dumps(v, ensure_ascii=False)   # a valid Python string literal
    raise TypeError(type(v))


def is_scalar(v):
    return v is None or isinstance(v, (bool, int, float, str))


def lit(v, level=0):
    pad, pad1 = IND * level, IND * (level + 1)
    if isinstance(v, dict):
        if not v:
            return "{}"
        rows = ["%s%s: %s," % (pad1, scalar(k), lit(x, level + 1)) for k, x in v.items()]
        return "{\n" + "\n".join(rows) + "\n" + pad + "}"
    if isinstance(v, list):
        if not v:
            return "[]"
        if all(is_scalar(x) for x in v):
            items = [scalar(x) for x in v]
            one = "[" + ", ".join(items) + "]"
            if len(one) + len(pad) <= WIDTH:
                return one
            lines, cur = [], ""
            for it in items:
                add = it + ","
                if cur and len(pad1) + len(cur) + 1 + len(add) > WIDTH:
                    lines.append(pad1 + cur)
                    cur = add
                else:
                    cur = (cur + " " + add) if cur else add
            lines.append(pad1 + cur)
            return "[\n" + "\n".join(lines) + "\n" + pad + "]"
        return "[\n" + "\n".join(pad1 + lit(x, level + 1) + "," for x in v) + "\n" + pad + "]"
    return scalar(v)


def outline(data):
    """Short 'what is inside' summary for the header."""
    def kind(v):
        if isinstance(v, dict):
            return "object with %d keys" % len(v)
        if isinstance(v, list):
            return "list of %d" % len(v)
        return type(v).__name__ if v is not None else "null"
    if isinstance(data, dict):
        ks = list(data.items())
        lines = ["  %-34s %s" % (k if len(k) <= 34 else k[:31] + "...", kind(v)) for k, v in ks[:25]]
        if len(ks) > 25:
            lines.append("  ... and %d more keys" % (len(ks) - 25))
        return "top level: object with %d keys\n" % len(ks) + "\n".join(lines)
    if isinstance(data, list):
        s = "top level: list of %d items" % len(data)
        if data and isinstance(data[0], dict):
            s += "; each item has keys: " + ", ".join(list(data[0].keys())[:15])
        return s
    return "top level: " + kind(data)


# ------------------------------------------------------------------ writer
TEMPLATE = '''r"""
PYTHON MIRROR OF A JSON FILE  (generated by build_mirror.py - do not edit by hand)

Source JSON : {rel}
Size        : {size} bytes
MD5         : {md5}
SHA-256     : {sha}

What it holds
    {what}

How the JSON was made (provenance)
    Evidence      : {evidence}
    Writer script : {writer}
    Working-tree  : {origin}
{note}
Contents
{outline}

Guarantee
    to_json_text() returns the source JSON byte for byte (checked when this file was built,
    and again every time check_mirror.py runs). DATA is the same data as the JSON, key order
    included. JSON null/true/false are None/True/False; NaN / Infinity appear as NAN / INF.

Use
    print the JSON text :  python3 {pyname}
    get DATA in Python  :  from grail_json import load
                           d = load("{key}")
"""

NAN = float("nan")
INF = float("inf")

SOURCE_JSON = "{rel}"
SOURCE_MD5 = "{md5}"
JSON_FORMAT = {fmt}

DATA = {data}


def to_json_text():
    """Rebuild the original JSON text from DATA (byte-identical to SOURCE_JSON)."""
    import json
    kw = {{"indent": JSON_FORMAT["indent"], "ensure_ascii": JSON_FORMAT["ensure_ascii"]}}
    if JSON_FORMAT["separators"]:
        kw["separators"] = tuple(JSON_FORMAT["separators"])
    return json.dumps(DATA, **kw) + ("\\n" if JSON_FORMAT["trailing_newline"] else "")


if __name__ == "__main__":
    import sys
    sys.stdout.write(to_json_text())
'''

EVIDENCE_TEXT = {
    "CONFIRMED": "CONFIRMED - the writer script's json.dump names this file",
    "CONFIRMED_ARGUMENT": "CONFIRMED_ARGUMENT - the writer script writes to a file named on its command line; "
                          "the structure matches; the exact command line was not saved",
    "EARLIER_VERSION": "EARLIER_VERSION - written by an earlier state of the writer script",
    "KEPT_COPY": "KEPT_COPY - a kept copy of an earlier output of the writer script",
    "NOT_RECORDED": "NOT_RECORDED - no saved script writes this file",
    "CONFIRMED+REPRODUCED": "CONFIRMED + REPRODUCED - re-run in 15_Run_in_VSCode gave the same bytes",
    "CONFIRMED+REPRODUCED_EXCEPT_SHAP": "CONFIRMED + REPRODUCED (except the randomly sampled SHAP values)",
}


def wrap(text, first, rest, width=96):
    words, lines, cur = text.split(), [], first
    for w in words:
        if len(cur) + len(w) + 1 > width and cur.strip():
            lines.append(cur.rstrip())
            cur = rest
        cur += w + " "
    lines.append(cur.rstrip())
    return "\n".join(lines)


def build():
    rows = list(csv.DictReader(open(os.path.join(HERE, "provenance.csv"), encoding="utf-8")))
    n = 0
    for r in rows:
        rel = r["json_file"]
        src = os.path.join(ROOT, rel)
        raw = open(src, "rb").read()
        text = raw.decode("utf-8")
        data = json.loads(text)
        fmt = detect_format(data, text)
        if fmt is None:
            sys.exit("STOP: no json.dumps setting reproduces %s byte for byte - no mirror written" % rel)
        key = rel[:-5]
        py_rel = key + ".py"
        dst = os.path.join(MIRROR, py_rel)
        writer = r["writer_script"] or "(none saved)"
        note = wrap(r["note"], "    Note          : ", "                    ") + "\n" if r["note"] else ""
        body = TEMPLATE.format(
            rel=rel, size=len(raw), md5=md5(raw), sha=sha256(raw),
            what=r["what_it_holds"], evidence=EVIDENCE_TEXT[r["evidence"]], writer=writer,
            origin=r["working_tree_origin"], note=note,
            outline="\n".join("    " + x for x in outline(data).splitlines()),
            pyname="16_JSON_Python_Mirror/mirror/" + py_rel, key=key,
            fmt=repr(fmt), data=lit(data))
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        tmp = dst + ".tmp"
        open(tmp, "w", encoding="utf-8").write(body)
        ns = runpy.run_path(tmp)
        if ns["to_json_text"]().encode("utf-8") != raw:
            os.remove(tmp)
            sys.exit("STOP: mirror of %s does not reproduce the file - not written" % rel)
        os.replace(tmp, dst)
        n += 1
        print("ok  %-78s indent=%s" % (py_rel, fmt["indent"]))
    print("\n%d mirror files written, each verified byte for byte." % n)


if __name__ == "__main__":
    build()
