r"""
PYTHON MIRROR OF A JSON FILE  (generated by build_mirror.py - do not edit by hand)

Source JSON : 03_CAD/gate1_grading.json
Size        : 1728 bytes
MD5         : 832ba227af03704d833af60b0e6ca93e
SHA-256     : b53cbdc0e9559dacf2603b4e00c74dc14b31eb92d25ddc08327c6aabd8fd1261

What it holds
    Gate 1: the channel grading law along the flow

How the JSON was made (provenance)
    Evidence      : CONFIRMED - the writer script's json.dump names this file
    Writer script : 02_geometry/gate1_grading2.py
    Working-tree  : 02_geometry/gate1_grading.json
    Note          : gate1_grading.py wrote an earlier version with different keys; the
                    delivered file has the CH05/CH06 keys written by gate1_grading2.py

Contents
    top level: object with 2 keys
      CH05                               list of 7
      CH06                               list of 7

Guarantee
    to_json_text() returns the source JSON byte for byte (checked when this file was built,
    and again every time check_mirror.py runs). DATA is the same data as the JSON, key order
    included. JSON null/true/false are None/True/False; NaN / Infinity appear as NAN / INF.

Use
    print the JSON text :  python3 16_JSON_Python_Mirror/mirror/03_CAD/gate1_grading.py
    get DATA in Python  :  from grail_json import load
                           d = load("03_CAD/gate1_grading")
"""

NAN = float("nan")
INF = float("inf")

SOURCE_JSON = "03_CAD/gate1_grading.json"
SOURCE_MD5 = "832ba227af03704d833af60b0e6ca93e"
JSON_FORMAT = {'indent': 1, 'separators': None, 'ensure_ascii': True, 'trailing_newline': False}

DATA = {
    "CH05": [
        {
            "xi": 0.0,
            "x": -549.95,
            "A": 29.987822969493703,
            "P": 21.5865208387598,
            "Dh": 5.5567681690787145,
        },
        {
            "xi": 0.1,
            "x": -440.0,
            "A": 25.516551565903,
            "P": 20.553887104863584,
            "Dh": 4.9657860697045715,
        },
        {
            "xi": 0.25,
            "x": -275.0,
            "A": 22.08314530060176,
            "P": 19.00473636590321,
            "Dh": 4.6479245753119915,
        },
        {
            "xi": 0.5,
            "x": 0.0,
            "A": 16.464654328099556,
            "P": 16.425323083020732,
            "Dh": 4.0095781970022815,
        },
        {
            "xi": 0.75,
            "x": 275.0,
            "A": 11.823107915061986,
            "P": 13.851951251573551,
            "Dh": 3.4141350053390944,
        },
        {
            "xi": 0.9,
            "x": 440.0,
            "A": 6.356057031460131,
            "P": 12.311568312971383,
            "Dh": 2.0650681927381855,
        },
        {
            "xi": 1.0,
            "x": 549.95,
            "A": 7.954429700987003,
            "P": 11.288385493722993,
            "Dh": 2.8186244013052653,
        },
    ],
    "CH06": [
        {
            "xi": 0.0,
            "x": 549.95,
            "A": 26.85486982903042,
            "P": 21.586548173068365,
            "Dh": 4.97622308369522,
        },
        {
            "xi": 0.1,
            "x": 440.0,
            "A": 25.537275265586874,
            "P": 20.553898842768497,
            "Dh": 4.969816278836399,
        },
        {
            "xi": 0.25,
            "x": 275.0,
            "A": 21.884131869744472,
            "P": 19.004741022520534,
            "Dh": 4.6060363240544815,
        },
        {
            "xi": 0.5,
            "x": 0.0,
            "A": 16.371285736651622,
            "P": 16.425325427019178,
            "Dh": 3.9868399099652145,
        },
        {
            "xi": 0.75,
            "x": -275.0,
            "A": 12.584395497626707,
            "P": 13.8519383914587,
            "Dh": 3.6339738575177094,
        },
        {
            "xi": 0.9,
            "x": -440.0,
            "A": 9.37738603086856,
            "P": 12.31157041540213,
            "Dh": 3.0466904592893136,
        },
        {
            "xi": 1.0,
            "x": -549.95,
            "A": 8.229019528184415,
            "P": 11.288449353985612,
            "Dh": 2.915907852402773,
        },
    ],
}


def to_json_text():
    """Rebuild the original JSON text from DATA (byte-identical to SOURCE_JSON)."""
    import json
    kw = {"indent": JSON_FORMAT["indent"], "ensure_ascii": JSON_FORMAT["ensure_ascii"]}
    if JSON_FORMAT["separators"]:
        kw["separators"] = tuple(JSON_FORMAT["separators"])
    return json.dumps(DATA, **kw) + ("\n" if JSON_FORMAT["trailing_newline"] else "")


if __name__ == "__main__":
    import sys
    sys.stdout.write(to_json_text())
