r"""
PYTHON MIRROR OF A JSON FILE  (generated by build_mirror.py - do not edit by hand)

Source JSON : 03_CAD/gate1_channels.json
Size        : 3550 bytes
MD5         : 778637df8f03943e93d6cd471062624b
SHA-256     : b7e2136d2035e85e8ae2f9f8a19bb6e56abd8e3d17f362e3f0bb9aa1f003923c

What it holds
    Gate 1: every channel measured on the STEP geometry

How the JSON was made (provenance)
    Evidence      : CONFIRMED - the writer script's json.dump names this file
    Writer script : 02_geometry/gate1_channels.py
    Working-tree  : 02_geometry/gate1_channels.json

Contents
    top level: list of 12 items; each item has keys: ch, tag, yc, vol, A_xm550, A_xp550, P_xm550, P_xp550, Dh_xm550, Dh_xp550, large_end

Guarantee
    to_json_text() returns the source JSON byte for byte (checked when this file was built,
    and again every time check_mirror.py runs). DATA is the same data as the JSON, key order
    included. JSON null/true/false are None/True/False; NaN / Infinity appear as NAN / INF.

Use
    print the JSON text :  python3 16_JSON_Python_Mirror/mirror/03_CAD/gate1_channels.py
    get DATA in Python  :  from grail_json import load
                           d = load("03_CAD/gate1_channels")
"""

NAN = float("nan")
INF = float("inf")

SOURCE_JSON = "03_CAD/gate1_channels.json"
SOURCE_MD5 = "778637df8f03943e93d6cd471062624b"
JSON_FORMAT = {'indent': 1, 'separators': None, 'ensure_ascii': True, 'trailing_newline': False}

DATA = [
    {
        "ch": 1,
        "tag": 117,
        "yc": -219.998,
        "vol": 18694.25359110991,
        "A_xm550": 28.06644304817016,
        "A_xp550": 7.862881361005626,
        "P_xm550": 21.58694985853138,
        "P_xp550": 11.287937872350444,
        "Dh_xm550": 5.200631535645694,
        "Dh_xp550": 2.786295052266573,
        "large_end": "-550",
    },
    {
        "ch": 2,
        "tag": 118,
        "yc": -179.998,
        "vol": 18694.89128687726,
        "A_xm550": 7.863106237848681,
        "A_xp550": 28.064287061473415,
        "P_xm550": 11.289022873800361,
        "P_xp550": 21.58666546392269,
        "Dh_xm550": 2.7861069379520633,
        "Dh_xp550": 5.200300548202154,
        "large_end": "+550",
    },
    {
        "ch": 3,
        "tag": 119,
        "yc": -139.998,
        "vol": 18694.161477040234,
        "A_xm550": 28.066149111482776,
        "A_xp550": 7.862878820698091,
        "P_xm550": 21.586940826837775,
        "P_xp550": 11.288330687523736,
        "Dh_xm550": 5.200579245872539,
        "Dh_xp550": 2.786197193669538,
        "large_end": "-550",
    },
    {
        "ch": 4,
        "tag": 124,
        "yc": -100.0,
        "vol": 18691.52608791677,
        "A_xm550": 7.864396694631467,
        "A_xp550": 28.064371099690327,
        "P_xm550": 11.289075051127375,
        "P_xp550": 21.58668172223722,
        "Dh_xm550": 2.7865513016838683,
        "Dh_xp550": 5.200312203756672,
        "large_end": "+550",
    },
    {
        "ch": 5,
        "tag": 120,
        "yc": -60.0,
        "vol": 18694.397048399405,
        "A_xm550": 28.06521488877261,
        "A_xp550": 7.863036803249631,
        "P_xm550": 21.586947783630897,
        "P_xp550": 11.287922809111295,
        "Dh_xm550": 5.200404461079782,
        "Dh_xp550": 2.7863538531297567,
        "large_end": "-550",
    },
    {
        "ch": 6,
        "tag": 125,
        "yc": -20.0,
        "vol": 18693.58525697455,
        "A_xm550": 7.861965908140382,
        "A_xp550": 28.064864235784082,
        "P_xm550": 11.287963789310764,
        "P_xp550": 21.586954604919057,
        "Dh_xm550": 2.7859642553372965,
        "Dh_xp550": 5.200337842817142,
        "large_end": "+550",
    },
    {
        "ch": 7,
        "tag": 121,
        "yc": 20.0,
        "vol": 18693.585256967526,
        "A_xm550": 28.064864235777716,
        "A_xp550": 7.86196590813687,
        "P_xm550": 21.58695460491589,
        "P_xp550": 11.287963789307952,
        "Dh_xm550": 5.200337842816725,
        "Dh_xp550": 2.785964255336746,
        "large_end": "-550",
    },
    {
        "ch": 8,
        "tag": 126,
        "yc": 60.0,
        "vol": 18694.397048402447,
        "A_xm550": 7.863036803250944,
        "A_xp550": 28.065214888774157,
        "P_xm550": 11.287922809112322,
        "P_xp550": 21.58694778363223,
        "Dh_xm550": 2.7863538531299685,
        "Dh_xp550": 5.200404461079748,
        "large_end": "+550",
    },
    {
        "ch": 9,
        "tag": 122,
        "yc": 100.0,
        "vol": 18691.526092935128,
        "A_xm550": 28.064371106351988,
        "A_xp550": 7.864396698493756,
        "P_xm550": 21.58668172531499,
        "P_xp550": 11.289075054351283,
        "Dh_xm550": 5.200312204249628,
        "Dh_xp550": 2.7865513022565964,
        "large_end": "-550",
    },
    {
        "ch": 10,
        "tag": 127,
        "yc": 140.002,
        "vol": 18694.161477075446,
        "A_xm550": 7.862878820696864,
        "A_xp550": 28.06614911151274,
        "P_xm550": 11.28833068752084,
        "P_xp550": 21.586940826840006,
        "Dh_xm550": 2.786197193669818,
        "Dh_xp550": 5.200579245877553,
        "large_end": "+550",
    },
    {
        "ch": 11,
        "tag": 123,
        "yc": 180.002,
        "vol": 18694.891143659082,
        "A_xm550": 28.064286889448404,
        "A_xp550": 7.863106140761482,
        "P_xm550": 21.586665378641037,
        "P_xp550": 11.2890227846968,
        "Dh_xm550": 5.200300536870629,
        "Dh_xp550": 2.7861069255420654,
        "large_end": "-550",
    },
    {
        "ch": 12,
        "tag": 128,
        "yc": 220.002,
        "vol": 18694.253591126166,
        "A_xm550": 7.862881361017596,
        "A_xp550": 28.066443048188763,
        "P_xm550": 11.287937872356192,
        "P_xp550": 21.58694985853751,
        "Dh_xm550": 2.7862950522693954,
        "Dh_xp550": 5.2006315356476644,
        "large_end": "+550",
    },
]


def to_json_text():
    """Rebuild the original JSON text from DATA (byte-identical to SOURCE_JSON)."""
    import json
    kw = {"indent": JSON_FORMAT["indent"], "ensure_ascii": JSON_FORMAT["ensure_ascii"]}
    if JSON_FORMAT["separators"]:
        kw["separators"] = tuple(JSON_FORMAT["separators"])
    return json.dumps(DATA, **kw) + ("\n" if JSON_FORMAT["trailing_newline"] else "")


if __name__ == "__main__":
    import sys
    sys.stdout.write(to_json_text())
