r"""
PYTHON MIRROR OF A JSON FILE  (generated by build_mirror.py - do not edit by hand)

Source JSON : 03_CAD/gate1_profile.json
Size        : 1721 bytes
MD5         : 896f0aaff491b41dca879d9e16c28b1f
SHA-256     : c7cba810f63d0be5b00fe396527c0567aa3a42ec6333c7f6c643a7d6f6991cbf

What it holds
    Gate 1: section profile along the flow

How the JSON was made (provenance)
    Evidence      : CONFIRMED - the writer script's json.dump names this file
    Writer script : 02_geometry/gate1_final.py
    Working-tree  : 02_geometry/gate1_profile.json

Contents
    top level: object with 2 keys
      CH05                               list of 7
      CH06                               list of 7

Guarantee
    to_json_text() returns the source JSON byte for byte (checked when this file was built,
    and again every time check_mirror.py runs). DATA is the same data as the JSON, key order
    included. JSON null/true/false are None/True/False; NaN / Infinity appear as NAN / INF.

Use
    print the JSON text :  python3 16_JSON_Python_Mirror/mirror/03_CAD/gate1_profile.py
    get DATA in Python  :  from grail_json import load
                           d = load("03_CAD/gate1_profile")
"""

NAN = float("nan")
INF = float("inf")

SOURCE_JSON = "03_CAD/gate1_profile.json"
SOURCE_MD5 = "896f0aaff491b41dca879d9e16c28b1f"
JSON_FORMAT = {'indent': 1, 'separators': None, 'ensure_ascii': True, 'trailing_newline': False}

DATA = {
    "CH05": [
        {
            "xi": 0.0,
            "x": -550.0,
            "A": 28.06521488877261,
            "P": 21.586520838759792,
            "Dh": 5.200507316284144,
        },
        {
            "xi": 0.1,
            "x": -440.0,
            "A": 25.542730241722992,
            "P": 20.55388710486359,
            "Dh": 4.970880712034058,
        },
        {
            "xi": 0.25,
            "x": -275.0,
            "A": 21.908012176667047,
            "P": 19.00473636590319,
            "Dh": 4.6110636327421375,
        },
        {
            "xi": 0.5,
            "x": 0.0,
            "A": 16.482427922123442,
            "P": 16.425323083020725,
            "Dh": 4.013906536587216,
        },
        {
            "xi": 0.75,
            "x": 275.0,
            "A": 11.831106545925518,
            "P": 13.85195125157339,
            "Dh": 3.4164447538267706,
        },
        {
            "xi": 0.9,
            "x": 440.0,
            "A": 9.430585095414889,
            "P": 12.311571749127879,
            "Dh": 3.063974377140897,
        },
        {
            "xi": 1.0,
            "x": 550.0,
            "A": 7.863036803249631,
            "P": 11.288385493722995,
            "Dh": 2.7862396469794346,
        },
    ],
    "CH06": [
        {
            "xi": 0.0,
            "x": 550.0,
            "A": 28.064864235784082,
            "P": 21.58654817306833,
            "Dh": 5.200435754855552,
        },
        {
            "xi": 0.1,
            "x": 440.0,
            "A": 25.542496235235532,
            "P": 20.553898842768575,
            "Dh": 4.97083233319932,
        },
        {
            "xi": 0.25,
            "x": 275.0,
            "A": 21.912713022343997,
            "P": 19.004741022520538,
            "Dh": 4.612051907758706,
        },
        {
            "xi": 0.5,
            "x": 0.0,
            "A": 16.46989230134924,
            "P": 16.42532542701917,
            "Dh": 4.010853209460741,
        },
        {
            "xi": 0.75,
            "x": -275.0,
            "A": 11.833491383799545,
            "P": 13.851938391458745,
            "Dh": 3.417136591105893,
        },
        {
            "xi": 0.9,
            "x": -440.0,
            "A": 9.41640869937683,
            "P": 12.311570415402132,
            "Dh": 3.059368831646897,
        },
        {
            "xi": 1.0,
            "x": -550.0,
            "A": 7.861965908140382,
            "P": 11.288449353985705,
            "Dh": 2.7858444190528235,
        },
    ],
}


def to_json_text():
    """Rebuild the original JSON text from DATA (byte-identical to SOURCE_JSON)."""
    import json
    kw = {"indent": JSON_FORMAT["indent"], "ensure_ascii": JSON_FORMAT["ensure_ascii"]}
    if JSON_FORMAT["separators"]:
        kw["separators"] = tuple(JSON_FORMAT["separators"])
    return json.dumps(DATA, **kw) + ("\n" if JSON_FORMAT["trailing_newline"] else "")


if __name__ == "__main__":
    import sys
    sys.stdout.write(to_json_text())
