r"""
PYTHON MIRROR OF A JSON FILE  (generated by build_mirror.py - do not edit by hand)

Source JSON : 03_CAD/strip_build.json
Size        : 445 bytes
MD5         : d8b5a57fe26e652d98ddc05ad8c2f1fb
SHA-256     : 2a9b7c49f8f851fc1ba2726541b1d032cc4b6128c96a6e64d56765983c0c6006

What it holds
    The reduced-domain 2- and 3-channel strip build

How the JSON was made (provenance)
    Evidence      : CONFIRMED - the writer script's json.dump names this file
    Writer script : 02_geometry/build_strips.py
    Working-tree  : 02_geometry/strip_build.json

Contents
    top level: object with 2 keys
      3ch                                object with 5 keys
      2ch                                object with 5 keys

Guarantee
    to_json_text() returns the source JSON byte for byte (checked when this file was built,
    and again every time check_mirror.py runs). DATA is the same data as the JSON, key order
    included. JSON null/true/false are None/True/False; NaN / Infinity appear as NAN / INF.

Use
    print the JSON text :  python3 16_JSON_Python_Mirror/mirror/03_CAD/strip_build.py
    get DATA in Python  :  from grail_json import load
                           d = load("03_CAD/strip_build")
"""

NAN = float("nan")
INF = float("inf")

SOURCE_JSON = "03_CAD/strip_build.json"
SOURCE_MD5 = "d8b5a57fe26e652d98ddc05ad8c2f1fb"
JSON_FORMAT = {'indent': 1, 'separators': None, 'ensure_ascii': True, 'trailing_newline': False}

DATA = {
    "3ch": {
        "name": "STRIP_3CH",
        "solid_vol": 281600.55374957283,
        "n_solid": 1,
        "fluid_vols": [18694.397048399405, 18693.58525697455, 18693.585256967526],
        "faces": {
            "40.0": 2200.0,
            "-80.0": 2200.0,
        },
    },
    "2ch": {
        "name": "STRIP_2CH",
        "solid_vol": 187736.13036024373,
        "n_solid": 1,
        "fluid_vols": [18694.397048399405, 18693.58525697455],
        "faces": {
            "-0.0": 2200.0,
            "-80.0": 2200.0,
        },
    },
}


def to_json_text():
    """Rebuild the original JSON text from DATA (byte-identical to SOURCE_JSON)."""
    import json
    kw = {"indent": JSON_FORMAT["indent"], "ensure_ascii": JSON_FORMAT["ensure_ascii"]}
    if JSON_FORMAT["separators"]:
        kw["separators"] = tuple(JSON_FORMAT["separators"])
    return json.dumps(DATA, **kw) + ("\n" if JSON_FORMAT["trailing_newline"] else "")


if __name__ == "__main__":
    import sys
    sys.stdout.write(to_json_text())
