r"""
PYTHON MIRROR OF A JSON FILE  (generated by build_mirror.py - do not edit by hand)

Source JSON : 03_CAD/tessellate_report.json
Size        : 290 bytes
MD5         : ae42bc406860145550924e5c071c7829
SHA-256     : 0edb0f17684bd6e2ca79d6bb61576bacb24a99ab0e9fd861f39c7b589cb76530

What it holds
    Tessellation report of the geometry

How the JSON was made (provenance)
    Evidence      : CONFIRMED - the writer script's json.dump names this file
    Writer script : 02_geometry/tessellate.py
    Working-tree  : 02_geometry/tessellate_report.json

Contents
    top level: object with 2 keys
      ch05                               object with 5 keys
      ch06                               object with 5 keys

Guarantee
    to_json_text() returns the source JSON byte for byte (checked when this file was built,
    and again every time check_mirror.py runs). DATA is the same data as the JSON, key order
    included. JSON null/true/false are None/True/False; NaN / Infinity appear as NAN / INF.

Use
    print the JSON text :  python3 16_JSON_Python_Mirror/mirror/03_CAD/tessellate_report.py
    get DATA in Python  :  from grail_json import load
                           d = load("03_CAD/tessellate_report")
"""

NAN = float("nan")
INF = float("inf")

SOURCE_JSON = "03_CAD/tessellate_report.json"
SOURCE_MD5 = "ae42bc406860145550924e5c071c7829"
JSON_FORMAT = {'indent': 1, 'separators': None, 'ensure_ascii': True, 'trailing_newline': False}

DATA = {
    "ch05": {
        "tris": 230976,
        "V": 18643.692268016184,
        "occV": 18694.397048399405,
        "A": 18071.07172943796,
        "occA": 18069.76033807715,
    },
    "ch06": {
        "tris": 230976,
        "V": 18643.603515728104,
        "occV": 18693.58525697455,
        "A": 18071.067753801897,
        "occA": 18069.56287035302,
    },
}


def to_json_text():
    """Rebuild the original JSON text from DATA (byte-identical to SOURCE_JSON)."""
    import json
    kw = {"indent": JSON_FORMAT["indent"], "ensure_ascii": JSON_FORMAT["ensure_ascii"]}
    if JSON_FORMAT["separators"]:
        kw["separators"] = tuple(JSON_FORMAT["separators"])
    return json.dumps(DATA, **kw) + ("\n" if JSON_FORMAT["trailing_newline"] else "")


if __name__ == "__main__":
    import sys
    sys.stdout.write(to_json_text())
