import numpy as np, gmsh, importlib.util, sys
spec=importlib.util.spec_from_file_location("T","/home/claude/grail_cfd/02_geometry/tessellate.py")
T=importlib.util.module_from_spec(spec); sys.modules["T"]=T; spec.loader.exec_module(T)
T.start(); low,up,fluid=T.find_parts()
wall,P,wt,ca,cb=T.channel_surface(fluid[-60.0], 48, 201)
print("grid P shape",P.shape)
print("ring closed? first==last dist %.3e" % np.linalg.norm(P[0,0]-P[0,-1]))
print("signed vol  wall  %12.3f" % T.signed_volume(wt))
print("signed vol  capA  %12.3f" % T.signed_volume(ca))
print("signed vol  capB  %12.3f" % T.signed_volume(cb))
print("sum               %12.3f   (OCC 18694.397)" % (T.signed_volume(wt)+T.signed_volume(ca)+T.signed_volume(cb)))
print("area capA %.4f  (expect 28.0652)" % T.area(ca))
print("area capB %.4f  (expect  7.8630)" % T.area(cb))
print("capA x:",P[0][:,0].min(),P[0][:,0].max())
print("capB x:",P[-1][:,0].min(),P[-1][:,0].max())
# check for repeated points in ring (seam duplication)
d=np.linalg.norm(np.diff(np.vstack([P[0],P[0][:1]]),axis=0),axis=1)
print("ring segment lengths: min %.4f max %.4f  n=%d" % (d.min(),d.max(),len(d)))
gmsh.finalize()
