r"""
PYTHON MIRROR OF A JSON FILE  (generated by build_mirror.py - do not edit by hand)

Source JSON : 12_Stages_3-5-6-7/surrogate/stage3_report.json
Size        : 4891 bytes
MD5         : 0f67769de13fe935b21944b5766b58e4
SHA-256     : dec799b8a5dd737dd87dc4366894a6355f21971eaeb32bdb6475e537b6e161cc

What it holds
    Stage 3 ANN / GPR accuracy and SHAP importances

How the JSON was made (provenance)
    Evidence      : CONFIRMED + REPRODUCED (except the randomly sampled SHAP values)
    Writer script : tools/stage3_ann.py
    Working-tree  : 21_surrogate/stage3_report.json
    Note          : re-run with 15_Run_in_VSCode: all accuracy numbers identical; SHAP
                    importances differ by up to ~3 % (random sampling in KernelExplainer) with
                    the same ranking; the recorded dataset path differs

Contents
    top level: object with 7 keys
      dataset                            str
      dataset_md5                        str
      n_train                            int
      n_test                             int
      inputs                             list of 9
      targets                            object with 4 keys
      shap_mean_abs_test                 object with 3 keys

Guarantee
    to_json_text() returns the source JSON byte for byte (checked when this file was built,
    and again every time check_mirror.py runs). DATA is the same data as the JSON, key order
    included. JSON null/true/false are None/True/False; NaN / Infinity appear as NAN / INF.

Use
    print the JSON text :  python3 16_JSON_Python_Mirror/mirror/12_Stages_3-5-6-7/surrogate/stage3_report.py
    get DATA in Python  :  from grail_json import load
                           d = load("12_Stages_3-5-6-7/surrogate/stage3_report")
"""

NAN = float("nan")
INF = float("inf")

SOURCE_JSON = "12_Stages_3-5-6-7/surrogate/stage3_report.json"
SOURCE_MD5 = "0f67769de13fe935b21944b5766b58e4"
JSON_FORMAT = {'indent': 1, 'separators': None, 'ensure_ascii': True, 'trailing_newline': False}

DATA = {
    "dataset": "/home/claude/grail_cfd/19_rev41/GRAIL_CFD_dataset_FINAL_rev4.2.csv",
    "dataset_md5": "13fd464c09a7c26fbe0fa75a5f5113b3",
    "n_train": 240,
    "n_test": 60,
    "inputs": [
        "G_T_W_m2", "T_in_K", "T_amb_K", "v_wind_m_s", "mdot_total_kg_s", "bridge_mm", "g_ratio",
        "lambda_G", "f_interdig",
    ],
    "targets": {
        "eta": {
            "best_architecture": [64, 32],
            "best_alpha": 0.01,
            "cv_R2_mean": 0.999426732288416,
            "ann_ensemble_test": {
                "R2": 0.9997468741204216,
                "RMSE": 0.0009974558586360578,
                "MAE": 0.0007005073645313895,
                "max_abs": 0.0033657912411189095,
            },
            "ann_single_test_R2_range": [0.9994349219438139, 0.9997712291277759],
            "ensemble_mean_pred_std": 0.0005597034778946646,
            "linear_test": {
                "R2": 0.8897138622762013,
                "RMSE": 0.02082024686337427,
                "MAE": 0.015680594794794184,
                "max_abs": 0.06295530996403687,
            },
            "gpr_test": {
                "R2": 0.999880270192251,
                "RMSE": 0.000686003850330026,
                "MAE": 0.00047955337665751184,
                "max_abs": 0.0027606187259592296,
            },
            "train_R2": 0.9999754885510668,
            "ann_ensemble_test_MAPE_pct": 0.1375174196650994,
        },
        "plate_std_K": {
            "best_architecture": [32, 32],
            "best_alpha": 0.01,
            "cv_R2_mean": 0.9992846847229702,
            "ann_ensemble_test": {
                "R2": 0.9995895919873762,
                "RMSE": 0.07267792019955967,
                "MAE": 0.03530440647053303,
                "max_abs": 0.41262124314887316,
            },
            "ann_single_test_R2_range": [0.9985868545990546, 0.9996865873995674],
            "ensemble_mean_pred_std": 0.031972782835527985,
            "linear_test": {
                "R2": 0.8518740165514929,
                "RMSE": 1.3807345698756324,
                "MAE": 0.9124489851285287,
                "max_abs": 6.2987404546198285,
            },
            "gpr_test": {
                "R2": 0.999962714228389,
                "RMSE": 0.021906154315659933,
                "MAE": 0.01722533085454708,
                "max_abs": 0.06375120654316557,
            },
            "train_R2": 0.9999662543407671,
            "ann_ensemble_test_MAPE_pct": 0.5301040871823222,
        },
        "log_dp_Pa": {
            "best_architecture": [64, 32],
            "best_alpha": 0.01,
            "cv_R2_mean": 0.999246498052918,
            "ann_ensemble_test": {
                "R2": 0.9997872813715832,
                "RMSE": 0.014784901576785523,
                "MAE": 0.009254671526488734,
                "max_abs": 0.06076060120688265,
            },
            "ann_single_test_R2_range": [0.9995026940066023, 0.9998187466292643],
            "ensemble_mean_pred_std": 0.008569446724234814,
            "linear_test": {
                "R2": 0.9747362448007844,
                "RMSE": 0.16112562982098758,
                "MAE": 0.11798266500719988,
                "max_abs": 0.6783037350747447,
            },
            "gpr_test": {
                "R2": 0.9999845818012045,
                "RMSE": 0.003980452962992471,
                "MAE": 0.00294823883740176,
                "max_abs": 0.01310879887596439,
            },
            "train_R2": 0.9999713067797226,
            "ann_ensemble_test_in_Pa": {
                "R2": 0.997972704079743,
                "RMSE": 1.2758266760271915,
                "MAE": 0.36459932790061195,
                "max_abs": 9.350128204891405,
            },
            "ann_ensemble_test_MAPE_pct": 0.9236787505582872,
        },
        "T_plate_mean_K": {
            "best_architecture": [64, 32],
            "best_alpha": 0.01,
            "cv_R2_mean": 0.9992292036428454,
            "ann_ensemble_test": {
                "R2": 0.999439184301239,
                "RMSE": 0.4524917967021024,
                "MAE": 0.2057352809192338,
                "max_abs": 2.989294569479796,
            },
            "ann_single_test_R2_range": [0.9991868856868389, 0.9995779284488897],
            "ensemble_mean_pred_std": 0.1343487406602871,
            "linear_test": {
                "R2": 0.8813015257455046,
                "RMSE": 6.582990030796365,
                "MAE": 4.398463146991756,
                "max_abs": 31.364223679174188,
            },
            "gpr_test": {
                "R2": 0.9999910739939539,
                "RMSE": 0.05708594798274845,
                "MAE": 0.04041911263094373,
                "max_abs": 0.17693663776753965,
            },
            "train_R2": 0.9999728393209629,
            "ann_ensemble_test_MAPE_pct": 0.059502447244328134,
        },
    },
    "shap_mean_abs_test": {
        "eta": {
            "T_in_K": 0.033826985330632574,
            "T_amb_K": 0.0234495806706386,
            "mdot_total_kg_s": 0.02242668773513616,
            "f_interdig": 0.0191634611382901,
            "G_T_W_m2": 0.009465091045978606,
            "v_wind_m_s": 0.0004695086032343191,
            "bridge_mm": 0.00011612576122043717,
            "g_ratio": 6.984504380979284e-05,
            "lambda_G": 6.100940904257681e-05,
        },
        "plate_std_K": {
            "mdot_total_kg_s": 2.3446056969843823,
            "G_T_W_m2": 1.3541112294520126,
            "T_in_K": 0.278545562234971,
            "f_interdig": 0.22990535442132434,
            "T_amb_K": 0.22832266996269146,
            "bridge_mm": 0.02097327393729447,
            "lambda_G": 0.006337989076870123,
            "v_wind_m_s": 0.0059080704552221825,
            "g_ratio": 0.00410529407597084,
        },
        "log_dp_Pa": {
            "g_ratio": 0.6161188285528062,
            "mdot_total_kg_s": 0.37477015168832495,
            "T_in_K": 0.19337981983884847,
            "lambda_G": 0.10820451304266344,
            "G_T_W_m2": 0.037235609802495476,
            "T_amb_K": 0.00698040676989876,
            "f_interdig": 0.006700557866862284,
            "v_wind_m_s": 0.0012035262365487015,
            "bridge_mm": 0.001090254306514101,
        },
    },
}


def to_json_text():
    """Rebuild the original JSON text from DATA (byte-identical to SOURCE_JSON)."""
    import json
    kw = {"indent": JSON_FORMAT["indent"], "ensure_ascii": JSON_FORMAT["ensure_ascii"]}
    if JSON_FORMAT["separators"]:
        kw["separators"] = tuple(JSON_FORMAT["separators"])
    return json.dumps(DATA, **kw) + ("\n" if JSON_FORMAT["trailing_newline"] else "")


if __name__ == "__main__":
    import sys
    sys.stdout.write(to_json_text())
