r"""
PYTHON MIRROR OF A JSON FILE  (generated by build_mirror.py - do not edit by hand)

Source JSON : 12_Stages_3-5-6-7/system_model/efficiency_correlations.json
Size        : 2416 bytes
MD5         : 7c84fa3c3beb95785c7bcc244f74d4d6
SHA-256     : 6c6c9e60ad161618aee92a8d423defc7cfba41c247cc30d65e3e09d4330b1e91

What it holds
    Stage 6 ISO 9806 efficiency correlations (eta0, a1, a2)

How the JSON was made (provenance)
    Evidence      : CONFIRMED + REPRODUCED - re-run in 15_Run_in_VSCode gave the same bytes
    Writer script : tools/stage6_fit.py
    Working-tree  : 22_system/efficiency_correlations.json
    Note          : re-run with 15_Run_in_VSCode: byte-identical

Contents
    top level: object with 2 keys
      alternating                        object with 11 keys
      parallel                           object with 11 keys

Guarantee
    to_json_text() returns the source JSON byte for byte (checked when this file was built,
    and again every time check_mirror.py runs). DATA is the same data as the JSON, key order
    included. JSON null/true/false are None/True/False; NaN / Infinity appear as NAN / INF.

Use
    print the JSON text :  python3 16_JSON_Python_Mirror/mirror/12_Stages_3-5-6-7/system_model/efficiency_correlations.py
    get DATA in Python  :  from grail_json import load
                           d = load("12_Stages_3-5-6-7/system_model/efficiency_correlations")
"""

NAN = float("nan")
INF = float("inf")

SOURCE_JSON = "12_Stages_3-5-6-7/system_model/efficiency_correlations.json"
SOURCE_MD5 = "7c84fa3c3beb95785c7bcc244f74d4d6"
JSON_FORMAT = {'indent': 1, 'separators': None, 'ensure_ascii': True, 'trailing_newline': False}

DATA = {
    "alternating": {
        "unconstrained_fit": {
            "eta0": 0.5965906020740813,
            "a1": 2.003882844904737,
            "a2": 0.00037944758755233723,
        },
        "a2_constraint": "not active",
        "eta0": 0.5965906020740813,
        "a1_W_m2K": 2.003882844904737,
        "a2_W_m2K2": 0.00037944758755233723,
        "fit_rms_pp": 0.15079148310931434,
        "fit_max_pp": 0.31825873777047153,
        "holdout": [
            {
                "G": 900.0,
                "T_in": 323.15,
                "T_amb": 303.15,
                "wind": 0.5,
                "eta_cht": 0.5296660030077477,
                "eta_fit": 0.52727967218396,
                "err_pp": 0.23863308237876968,
            },
            {
                "G": 900.0,
                "T_in": 323.15,
                "T_amb": 303.15,
                "wind": 4.9,
                "eta_cht": 0.5272749370461803,
                "eta_fit": 0.5273910029866954,
                "err_pp": -0.011606594051505326,
            },
            {
                "G": 700.0,
                "T_in": 332.15,
                "T_amb": 288.15,
                "wind": 3.0,
                "eta_cht": 0.4500298940689136,
                "eta_fit": 0.448497952391192,
                "err_pp": 0.15319416777215822,
            },
        ],
        "inlet_form": {
            "eta0": 0.5705061699379035,
            "a1": 1.896620674432091,
            "a2": 0.0016426932614049745,
        },
        "wind_sensitivity_eta": {
            "0.5": 0.52967,
            "3.0": 0.52791,
            "4.9": 0.52727,
        },
        "Tm_minus_Ta_range_K": [-3.0456582602445224, 39.50653768022278],
    },
    "parallel": {
        "unconstrained_fit": {
            "eta0": 0.6368712481714353,
            "a1": 2.1266065544487778,
            "a2": -0.000613835674214261,
        },
        "a2_constraint": "a2 >= 0 enforced",
        "eta0": 0.6367728001004268,
        "a1_W_m2K": 2.1040764409992594,
        "a2_W_m2K2": 0.0,
        "fit_rms_pp": 0.22889514095565394,
        "fit_max_pp": 0.4338948540310916,
        "holdout": [
            {
                "G": 900.0,
                "T_in": 323.15,
                "T_amb": 303.15,
                "wind": 0.5,
                "eta_cht": 0.5642557775365554,
                "eta_fit": 0.5627488521554274,
                "err_pp": 0.15069253811280658,
            },
            {
                "G": 900.0,
                "T_in": 323.15,
                "T_amb": 303.15,
                "wind": 4.9,
                "eta_cht": 0.5638195331555129,
                "eta_fit": 0.5627699329177165,
                "err_pp": 0.10496002377964331,
            },
            {
                "G": 700.0,
                "T_in": 332.15,
                "T_amb": 288.15,
                "wind": 3.0,
                "eta_cht": 0.4808565098519172,
                "eta_fit": 0.481279999687113,
                "err_pp": -0.04234898351958005,
            },
        ],
        "inlet_form": {
            "eta0": 0.6078876624462394,
            "a1": 1.955438184215686,
            "a2": 0.002699953015200967,
        },
        "wind_sensitivity_eta": {
            "0.5": 0.56426,
            "3.0": 0.56394,
            "4.9": 0.56382,
        },
        "Tm_minus_Ta_range_K": [-2.6114098001526145, 40.23571927114938],
    },
}


def to_json_text():
    """Rebuild the original JSON text from DATA (byte-identical to SOURCE_JSON)."""
    import json
    kw = {"indent": JSON_FORMAT["indent"], "ensure_ascii": JSON_FORMAT["ensure_ascii"]}
    if JSON_FORMAT["separators"]:
        kw["separators"] = tuple(JSON_FORMAT["separators"])
    return json.dumps(DATA, **kw) + ("\n" if JSON_FORMAT["trailing_newline"] else "")


if __name__ == "__main__":
    import sys
    sys.stdout.write(to_json_text())
